name: 'Deploy to Play-with-Docker'
description: 'Deploy static site to Play-with-Docker'

inputs:
  pwd_host:
    required: true
  pwd_username:
    required: true
    default: 'root'
  pwd_password:
    required: true
  site_directory:
    required: true
    default: 'site'

runs:
  using: "composite"
  steps:
    - name: Install SSH client
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Test connection to PWD
      shell: bash
      env:
        PWD_HOST: ${{ inputs.pwd_host }}
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        echo "Testing connection to PWD..."
        sshpass -p "$PWD_PASSWORD" ssh -o StrictHostKeyChecking=no root@$PWD_HOST "echo 'Connection successful!'"

    - name: Deploy files
      shell: bash
      env:
        PWD_HOST: ${{ inputs.pwd_host }}
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        echo "Deploying files to PWD..."
        sshpass -p "$PWD_PASSWORD" ssh -o StrictHostKeyChecking=no root@$PWD_HOST "mkdir -p /root/static-site"
        sshpass -p "$PWD_PASSWORD" scp -o StrictHostKeyChecking=no -r ${{ inputs.site_directory }}/* root@$PWD_HOST:/root/static-site/
        echo "Files deployed successfully!"

    - name: Start web server
      shell: bash
      env:
        PWD_HOST: ${{ inputs.pwd_host }}
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        echo "Starting web server on PWD..."
        sshpass -p "$PWD_PASSWORD" ssh -o StrictHostKeyChecking=no root@$PWD_HOST "
          docker run -d --name my-static-site -p 8080:80 -v /root/static-site:/usr/share/nginx/html nginx:alpine
          echo 'Web server started on port 8080'
        "