name: 'Deploy to Play-with-Docker'
description: 'Deploy static site to Play-with-Docker instance via SCP'

inputs:
  pwd_host:
    description: 'Play-with-Docker instance IP address'
    required: true
  pwd_username:
    description: 'SSH username'
    required: true
    default: 'root'
  pwd_password:
    description: 'SSH password'
    required: true
  site_directory:
    description: 'Directory containing built static site'
    required: true
    default: 'site'
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'

runs:
  using: "composite"
  steps:
    - name: Install SSH dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Verify site directory exists
      shell: bash
      run: |
        echo "Checking site directory: ${{ inputs.site_directory }}"
        ls -la ${{ inputs.site_directory }}/

    - name: Create directory on PWD instance
      shell: bash
      env:
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        sshpass -p "$PWD_PASSWORD" ssh -o StrictHostKeyChecking=no -p ${{ inputs.ssh_port }} \
          ${{ inputs.pwd_username }}@${{ inputs.pwd_host }} \
          "mkdir -p /root/static-site && echo 'Directory created'"

    - name: Copy static files to PWD
      shell: bash
      env:
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        sshpass -p "$PWD_PASSWORD" scp -o StrictHostKeyChecking=no -P ${{ inputs.ssh_port }} -r \
          ${{ inputs.site_directory }}/* \
          ${{ inputs.pwd_username }}@${{ inputs.pwd_host }}:/root/static-site/

    - name: Start web server on PWD
      shell: bash
      env:
        PWD_PASSWORD: ${{ inputs.pwd_password }}
      run: |
        sshpass -p "$PWD_PASSWORD" ssh -o StrictHostKeyChecking=no -p ${{ inputs.ssh_port }} \
          ${{ inputs.pwd_username }}@${{ inputs.pwd_host }} << 'EOF'
          # Stop existing container if any
          docker stop static-site 2>/dev/null || true
          docker rm static-site 2>/dev/null || true
          
          # Start new container
          docker run -d \
            --name static-site \
            -p 8080:80 \
            -v /root/static-site:/usr/share/nginx/html \
            nginx:alpine
          
          # Verify deployment
          sleep 3
          docker ps
          echo "Deployment completed! Site is running on port 8080"
        EOF